### ISSUE TITLE
Virtual Machine: System.Net.HttpListenerException (0x80004005) Error

### ISSUE THREAD

**Issue by chKaze** [japanesemediamanager/jmmserver#150]
Hey I moved my JMM server to a virtual machine and I get this error when trying to start the server:

`[2015-06-27 06:34:28:641] Info|BackgroundWorker.WorkerThreadStart => MainWindow.workerSetupDB_DoWork => MainWindow.AniDBDispose Disposing...
[2015-06-27 06:34:28:643] Info|MainWindow.workerSetupDB_DoWork => MainWindow.AniDBDispose => AniDBHelper.Dispose ANIDBLIB DISPOSING...
[2015-06-27 06:34:30:645] Info|StackBuilderSink._PrivateProcessMessage => BackgroundWorker.WorkerThreadStart => MainWindow.workerSetupDB_DoWork Setting up database...
[2015-06-27 06:34:30:798] Info|StackBuilderSink._PrivateProcessMessage => BackgroundWorker.WorkerThreadStart => MainWindow.workerSetupDB_DoWork Initializing Session Factory...
[2015-06-27 06:34:30:798] Info|StackBuilderSink._PrivateProcessMessage => BackgroundWorker.WorkerThreadStart => MainWindow.workerSetupDB_DoWork Initializing Hosts...
[2015-06-27 06:34:30:798] Info|MainWindow.SetupAniDBProcessor => AniDBHelper.Init => AniDBHelper.BindToLocalPort -------- Local IP Addresses --------
[2015-06-27 06:34:30:812] Info|MainWindow.SetupAniDBProcessor => AniDBHelper.Init => AniDBHelper.BindToLocalPort -------- End Local IP Addresses --------
[2015-06-27 06:34:30:812] Info|MainWindow.SetupAniDBProcessor => AniDBHelper.Init => AniDBHelper.BindToLocalPort BindToLocalPort: Bound to local address: 0.0.0.0:4556 - Port: 4556 (InterNetwork)
[2015-06-27 06:34:30:812] Info|MainWindow.SetupAniDBProcessor => AniDBHelper.Init => AniDBHelper.BindToRemotePort BindToRemotePort: Bound to remote address: 50.30.46.102 : 9000
[2015-06-27 06:34:30:837] Info|MainWindow.workerSetupDB_DoWork => MainWindow.SetupAniDBProcessor => AniDBHelper.Init starting logout timer...
[2015-06-27 06:34:31:006] Error|StackBuilderSink._PrivateProcessMessage => BackgroundWorker.WorkerThreadStart => MainWindow.workerSetupDB_DoWork System.Net.HttpListenerException (0x80004005): The process cannot access the file because it is being used by another process
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at JMMServer.FileServer.FileServer..ctor(Int32 port, Int32 maxthreads) in c:\Projects\GitHub\JMMServer\JMMServer\FileServer\FileServer.cs:line 192
   at JMMServer.MainWindow.StartFileHost() in c:\Projects\GitHub\JMMServer\JMMServer\MainWindow.xaml.cs:line 2318
   at JMMServer.MainWindow.workerSetupDB_DoWork(Object sender, DoWorkEventArgs e) in c:\Projects\GitHub\JMMServer\JMMServer\MainWindow.xaml.cs:line 861
`

**Comment by chKaze** [comment]
I think the problem was that I had assigned only 1 core to the VM, assigning 4 cores seems to have fixed the problem.

**Comment by jmediamanager** [comment]
Great to hear
