### ISSUE TITLE
Can't pull episode info from anidb

### ISSUE THREAD

**Issue by enlait** [japanesemediamanager/jmmserver#151]
I try to update info on episodes I downloaded last two weeks, but they end up in "Unrecognized" with no error indications in GUI.

My log is full of these:
```
[2015-06-28 20:14:27:290] Info|CommandRequest_ProcessFile.ProcessFile_AniDB => AzureWebAPI.Get_CrossRefFileEpisode => JMMService.LogToDatabase Cache HTTP - Got File/Episode Cross Ref From Cache: E5872C7F7568389529676958A646DA8D - 324,9624
[2015-06-28 20:14:27:339] Info|BackgroundWorker.WorkerThreadStart => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_ProcessFile.ProcessCommand Processing File: 19652
[2015-06-28 20:14:27:339] Error|AniDBHelper.Login => AniDBCommand_Login.Process => AniDBUDPCommand.ProcessCommand System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, EndPoint& remoteEP)
   at AniDBAPI.Commands.AniDBUDPCommand.ProcessCommand(Socket& soUDP, IPEndPoint& remoteIpEndPoint, String sessionID, Encoding enc) in c:\Projects\GitHub\JMMServer\JMMServer\AniDB_API\Commands\AniDBUDPCommand.cs:line 123
```

Client 3.4.3.1
Server 3.4.2.19

**Comment by jmediamanager** [comment]
Hi can you do a manual update of your JMM Server using these files
The auto update seems to be broken

http://www.jmediamanager.org/jmmserver/jmmserver.all.to.3.4.3.2.zip
