### ISSUE TITLE
3.5 compatibility with 3.4 database

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver#239]
Is 3.5 compatible with database from 3.4 ?

![111](https://cloud.githubusercontent.com/assets/6052025/14815471/dc13d758-0bab-11e6-9163-866459261bb6.png)

Because this is after serverly minuts of doing nothing than starting server

**Comment by da3dsoul** [comment]
It should be. Mine worked fine. Looks like you have a corrupted db. Think it might've happened when you recreated groups?

**Comment by bigretromike** [comment]
common issue with jmm, had reimport collection 4 times ;-)

**Comment by bigretromike** [comment]
error is about that its unable to comit select and not that got errors from that table :+1:

**Comment by ElementalCrisis** [comment]
Hmm, had no problems myself using my old 3.4 database. When I get home later I'll run some tests just to check again.

**Comment by jmediamanager** [comment]
Can you attach the logs, might be a mysql specific error

**Comment by ElementalCrisis** [comment]
OK just ran some tests, created database on 3.4 and had it hash files. Was able to use it on 3.5 with no problems and even could switch back to 3.4.

**Comment by bigretromike** [comment]
I used old db from 3.4 then in 3.5 I regrouped them by related series - took some time ~35 minuts, then when running in same not restarted 3.5 I had that error.

This is the interesting part from log:

```
[2016-04-26 12:07:55:548] Error|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => StatsCache.InitStats NHibernate.Exceptions.GenericADOException: could not execute query
[ SELECT this_.AniDB_CharacterID as AniDB1_151_0_, this_.CharDescription as CharDesc2_151_0_, this_.CharID as CharID151_0_, this_.PicName as PicName151_0_, this_.CharKanjiName as CharKanj5_151_0_, this_.CharName as CharName151_0_, this_.CreatorListRaw as CreatorL7_151_0_ FROM `AniDB_Character` this_ WHERE this_.CharID = ? ]
Positional parameters:  #0>72496
[SQL: SELECT this_.AniDB_CharacterID as AniDB1_151_0_, this_.CharDescription as CharDesc2_151_0_, this_.CharID as CharID151_0_, this_.PicName as PicName151_0_, this_.CharKanjiName as CharKanj5_151_0_, this_.CharName as CharName151_0_, this_.CreatorListRaw as CreatorL7_151_0_ FROM `AniDB_Character` this_ WHERE this_.CharID = ?] ---> MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts. ---> System.Net.Sockets.SocketException: Próba przeprowadzenia operacji, wykonywanej przez gniazdo, na nieosiągalnym hoście 10.1.1.100:3306
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at MySql.Data.Common.MyNetworkStream.CreateSocketStream(MySqlConnectionStringBuilder settings, IPAddress ip, Boolean unix)
   at MySql.Data.Common.MyNetworkStream.CreateStream(MySqlConnectionStringBuilder settings, Boolean unix)
   at MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at NHibernate.Connection.DriverConnectionProvider.GetConnection() in d:\CSharp\NH\nhibernate\src\NHibernate\Connection\DriverConnectionProvider.cs:line 46
   at NHibernate.AdoNet.ConnectionManager.GetConnection() in d:\CSharp\NH\nhibernate\src\NHibernate\AdoNet\ConnectionManager.cs:line 196
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd) in d:\CSharp\NH\nhibernate\src\NHibernate\AdoNet\AbstractBatcher.cs:line 100
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd) in d:\CSharp\NH\nhibernate\src\NHibernate\AdoNet\AbstractBatcher.cs:line 235
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1337
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 401
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 236
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1665
   --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1674
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1589
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1585
   at NHibernate.Loader.Criteria.CriteriaLoader.List(ISessionImplementor session) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Criteria\CriteriaLoader.cs:line 75
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results) in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\SessionImpl.cs:line 1923
   at NHibernate.Impl.CriteriaImpl.List(IList results) in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\CriteriaImpl.cs:line 246
   at NHibernate.Impl.CriteriaImpl.List() in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\CriteriaImpl.cs:line 238
   at NHibernate.Impl.CriteriaImpl.UniqueResult() in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\CriteriaImpl.cs:line 408
   at NHibernate.Impl.CriteriaImpl.UniqueResult[T]() in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\CriteriaImpl.cs:line 262
   at JMMServer.Repositories.AniDB_CharacterRepository.GetByCharID(ISession session, Int32 id) in c:\bin\jmmserver\JMMServer\Repositories\AniDB_CharacterRepository.cs:line 56
   at JMMServer.Entities.AniDB_Anime_Character.GetCharacter(ISession session) in c:\bin\jmmserver\JMMServer\Entities\AniDB_Anime_Character.cs:line 40
   at JMMServer.Plex.PlexHelper.FillSerie(Video p, AnimeSeries aser, AniDB_Anime anidb, Contract_AnimeSeries ser, Int32 userid) in c:\bin\jmmserver\JMMServer\Plex\PlexHelper.cs:line 741
   at JMMServer.Plex.PlexHelper.FromSerieWithPossibleReplacement(Contract_AnimeSeries cserie, AnimeSeries ser, AniDB_Anime anidb, Int32 userid) in c:\bin\jmmserver\JMMServer\Plex\PlexHelper.cs:line 670
   at JMMServer.Plex.PlexHelper.VideoFromAnimeGroup(ISession session, AnimeGroup grp, Int32 userid, List`1 allSeries) in c:\bin\jmmserver\JMMServer\Plex\PlexHelper.cs:line 573
   at JMMServer.StatsCache.UpdatePlexAnimeGroup(ISession session, AnimeGroup grp, List`1 allSeries) in c:\bin\jmmserver\JMMServer\StatsCache.cs:line 123
   at JMMServer.StatsCache.InitStats() in c:\bin\jmmserver\JMMServer\StatsCache.cs:line 1240
[2016-04-26 12:08:00:659] Error|ServerInfo.RefreshAdminMessages => AzureWebAPI.Get_AdminMessages => AzureWebAPI.GetDataJson Error(1) in AzureWebAPI.GetData: System.Net.WebException: Nie można rozpoznać nazwy zdalnej: 'jmm.azurewebsites.net'
   w System.Net.HttpWebRequest.GetResponse()
   w JMMServer.Providers.Azure.AzureWebAPI.GetDataJson(String uri) w c:\bin\jmmserver\JMMServer\Providers\Azure\AzureWebAPI.cs:wiersz 548
[2016-04-26 12:08:00:800] Error|MainWindow.CheckForAdminMesages => ServerInfo.RefreshAdminMessages => AzureWebAPI.Get_AdminMessages Error(2) in XMLServiceQueue.SendData: {0}
[2016-04-26 12:08:14:490] Error|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork NHibernate.Exceptions.GenericADOException: could not execute query
[ SELECT this_.ImportFolderID as ImportFo1_188_0_, this_.ImportFolderType as ImportFo2_188_0_, this_.ImportFolderLocation as ImportFo3_188_0_, this_.ImportFolderName as ImportFo4_188_0_, this_.IsDropDestination as IsDropDe5_188_0_, this_.IsDropSource as IsDropSo6_188_0_, this_.IsWatched as IsWatched188_0_ FROM `ImportFolder` this_ ]
[SQL: SELECT this_.ImportFolderID as ImportFo1_188_0_, this_.ImportFolderType as ImportFo2_188_0_, this_.ImportFolderLocation as ImportFo3_188_0_, this_.ImportFolderName as ImportFo4_188_0_, this_.IsDropDestination as IsDropDe5_188_0_, this_.IsDropSource as IsDropSo6_188_0_, this_.IsWatched as IsWatched188_0_ FROM `ImportFolder` this_] ---> MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts. ---> System.Net.Sockets.SocketException: Próba przeprowadzenia operacji, wykonywanej przez gniazdo, na nieosiągalnym hoście 10.1.1.100:3306
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at MySql.Data.Common.MyNetworkStream.CreateSocketStream(MySqlConnectionStringBuilder settings, IPAddress ip, Boolean unix)
   at MySql.Data.Common.MyNetworkStream.CreateStream(MySqlConnectionStringBuilder settings, Boolean unix)
   at MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at NHibernate.Connection.DriverConnectionProvider.GetConnection() in d:\CSharp\NH\nhibernate\src\NHibernate\Connection\DriverConnectionProvider.cs:line 46
   at NHibernate.AdoNet.ConnectionManager.GetConnection() in d:\CSharp\NH\nhibernate\src\NHibernate\AdoNet\ConnectionManager.cs:line 196
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd) in d:\CSharp\NH\nhibernate\src\NHibernate\AdoNet\AbstractBatcher.cs:line 100
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd) in d:\CSharp\NH\nhibernate\src\NHibernate\AdoNet\AbstractBatcher.cs:line 235
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1337
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 401
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 236
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1665
   --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1674
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1589
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1585
   at NHibernate.Loader.Criteria.CriteriaLoader.List(ISessionImplementor session) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Criteria\CriteriaLoader.cs:line 75
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results) in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\SessionImpl.cs:line 1923
   at NHibernate.Impl.CriteriaImpl.List(IList results) in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\CriteriaImpl.cs:line 246
   at NHibernate.Impl.CriteriaImpl.List[T]() in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\CriteriaImpl.cs:line 258
   at JMMServer.Repositories.ImportFolderRepository.GetAll() in c:\bin\jmmserver\JMMServer\Repositories\ImportFolderRepository.cs:line 49
   at JMMServer.MainWindow.StartWatchingFiles() in c:\bin\jmmserver\JMMServer\MainWindow.xaml.cs:line 1998
   at JMMServer.MainWindow.workerSetupDB_DoWork(Object sender, DoWorkEventArgs e) in c:\bin\jmmserver\JMMServer\MainWindow.xaml.cs:line 981
```

**Comment by jmediamanager** [comment]
The log basically says it can't connect to the MySQL host.
Can you check the details please

**Comment by bigretromike** [comment]
I will try to recreate it, mean while i will close this until I can recreate this with my current database.
