### ISSUE TITLE
after upgrading Server can not be accessed anymore

### ISSUE THREAD

**Issue by yhoogi** [japanesemediamanager/jmmserver#383]
After upgrading to 3.6.0.2 server can not access the database anymore

Error report shows 
"Failed to Start. Please review database settings"
DB Server: MySQL56
Login & PW are correct

Update:
Newly created DB does not show problems. (migration problem?)

_________________________________________________________________________________________________

[2016-09-02 20:54:39:801] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog -------------------- SYSTEM INFO -----------------------
[2016-09-02 20:54:39:863] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog JMM Server Version: v3.6.0.2
[2016-09-02 20:54:42:159] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Database Version: 53
[2016-09-02 20:54:42:191] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Operating System: Windows 8 / 2012 Server 64-bit
[2016-09-02 20:54:42:206] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Screen Size: 1920x1080
[2016-09-02 20:54:42:237] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MediaInfo DLL 0.7.86.0 (C:\Program Files (x86)\JMM Server\x64\MediaInfo.dll)
[2016-09-02 20:54:42:253] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Hasher DLL found at C:\Program Files (x86)\JMM Server\x64\hasher.dll
[2016-09-02 20:54:42:269] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog -------------------------------------------------------
[2016-09-02 20:54:42:284] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog ----------------- SERVER SETTINGS ----------------------
[2016-09-02 20:54:42:300] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog DatabaseType: MySQL
[2016-09-02 20:54:42:316] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MSSQL DatabaseServer: localhost
[2016-09-02 20:54:42:331] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MSSQL DatabaseName: JMMServer
[2016-09-02 20:54:42:347] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MSSQL DatabaseUsername: ***HIDDEN***
[2016-09-02 20:54:42:362] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MSSQL DatabasePassword: ***HIDDEN***
[2016-09-02 20:54:42:378] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog SQLITE DatabaseFile: 
[2016-09-02 20:54:42:394] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MySQL_Hostname: localhost
[2016-09-02 20:54:42:409] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MySQL_SchemaName: jmmserver
[2016-09-02 20:54:42:425] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MySQL_Username: ***HIDDEN***
[2016-09-02 20:54:42:441] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MySQL_Password: ***HIDDEN***
[2016-09-02 20:54:42:456] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_Username: ***HIDDEN***
[2016-09-02 20:54:42:472] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_Password: ***HIDDEN***
[2016-09-02 20:54:42:487] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_ServerAddress: api.anidb.info
[2016-09-02 20:54:42:503] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_ServerPort: 9000
[2016-09-02 20:54:42:534] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_ClientPort: 4556
[2016-09-02 20:54:42:550] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_AVDumpKey: NOT SET
[2016-09-02 20:54:42:566] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_AVDumpClientPort: 4557
[2016-09-02 20:54:42:581] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_DownloadRelatedAnime: True
[2016-09-02 20:54:42:597] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_DownloadSimilarAnime: False
[2016-09-02 20:54:42:612] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_DownloadReviews: False
[2016-09-02 20:54:42:628] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_DownloadReleaseGroups: False
[2016-09-02 20:54:42:644] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_AddFiles: True
[2016-09-02 20:54:42:659] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_StorageState: HDD
[2016-09-02 20:54:42:675] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_ReadUnwatched: True
[2016-09-02 20:54:42:691] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_ReadWatched: True
[2016-09-02 20:54:42:706] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_SetWatched: True
[2016-09-02 20:54:42:722] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_SetUnwatched: True
[2016-09-02 20:54:42:737] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_UpdateFrequency: HoursSix
[2016-09-02 20:54:42:769] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_Calendar_UpdateFrequency: Daily
[2016-09-02 20:54:42:784] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_Anime_UpdateFrequency: HoursSix
[2016-09-02 20:54:42:800] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_Address: omm.hobbydb.net.leaf.arvixe.com
[2016-09-02 20:54:42:816] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_Anonymous: True
[2016-09-02 20:54:42:831] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_XRefFileEpisode_Get: True
[2016-09-02 20:54:42:847] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_XRefFileEpisode_Send: False
[2016-09-02 20:54:42:862] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_TvDB_Get: True
[2016-09-02 20:54:42:878] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_TvDB_Send: False
[2016-09-02 20:54:42:894] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_MAL_Get: True
[2016-09-02 20:54:42:909] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_MAL_Send: False
[2016-09-02 20:54:42:925] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_AutoFanart: True
[2016-09-02 20:54:42:941] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_AutoFanartAmount: 10
[2016-09-02 20:54:43:003] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_AutoWideBanners: True
[2016-09-02 20:54:43:019] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_AutoPosters: True
[2016-09-02 20:54:43:034] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_UpdateFrequency: Daily
[2016-09-02 20:54:43:050] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_Language: en
[2016-09-02 20:54:43:066] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MovieDB_AutoFanart: True
[2016-09-02 20:54:43:081] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MovieDB_AutoFanartAmount: 10
[2016-09-02 20:54:43:128] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MovieDB_AutoPosters: True
[2016-09-02 20:54:43:144] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog VideoExtensions: MKV,AVI,MP4,MOV,OGM,WMV,MPG,MPEG,ts
[2016-09-02 20:54:43:159] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog DefaultSeriesLanguage: Romaji
[2016-09-02 20:54:43:175] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog DefaultEpisodeLanguage: Romaji
[2016-09-02 20:54:43:191] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog RunImportOnStart: False
[2016-09-02 20:54:43:206] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Hash_CRC32: True
[2016-09-02 20:54:43:284] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Hash_MD5: False
[2016-09-02 20:54:43:300] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Hash_SHA1: False
[2016-09-02 20:54:43:316] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Import_UseExistingFileWatchedStatus: True
[2016-09-02 20:54:43:331] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_IsEnabled: True
[2016-09-02 20:54:43:550] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_AuthToken: NOT SET
[2016-09-02 20:54:43:597] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_RefreshToken: NOT SET
[2016-09-02 20:54:43:613] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_UpdateFrequency: HoursSix
[2016-09-02 20:54:43:628] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_SyncFrequency: HoursSix
[2016-09-02 20:54:43:644] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AutoGroupSeries: True
[2016-09-02 20:54:43:659] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AutoGroupSeriesRelationExclusions: 
[2016-09-02 20:54:43:675] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog LanguagePreference: x-jat,en
[2016-09-02 20:54:43:691] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog LanguageUseSynonyms: True
[2016-09-02 20:54:43:706] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog EpisodeTitleSource: AniDB
[2016-09-02 20:54:43:722] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog SeriesDescriptionSource: AniDB
[2016-09-02 20:54:43:738] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog SeriesNameSource: AniDB
[2016-09-02 20:54:43:753] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog BaseImagesPath: C:\ProgramData\JMMServer\Images
[2016-09-02 20:54:43:769] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog BaseImagesPathIsDefault: False
[2016-09-02 20:54:43:784] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog -------------------------------------------------------
[2016-09-02 20:54:44:331] Info|UIElement.RaiseEventImpl => EventRoute.InvokeHandlersImpl => MainWindow.MainWindow_Loaded Clearing Cache...
[2016-09-02 20:54:44:378] Info|UIElement.RaiseEventImpl => EventRoute.InvokeHandlersImpl => MainWindow.MainWindow_Loaded Initializing DB...
[2016-09-02 20:54:44:394] Info|UIElement.RaiseEventImpl => EventRoute.InvokeHandlersImpl => MainWindow.MainWindow_Loaded Checking for updates...
[2016-09-02 20:54:44:394] Info|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => MainWindow.AniDBDispose Disposing...
[2016-09-02 20:54:44:425] Info|MainWindow.workerSetupDB_DoWork => MainWindow.AniDBDispose => AniDBHelper.Dispose ANIDBLIB DISPOSING...
[2016-09-02 20:54:46:470] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork Setting up database...
[2016-09-02 20:54:50:024] Error|VideoLocalRepository.Save => Helper.GenerateMediaFromVideoLocal => MediaInfoReader.ReadMediaInfo Unable to read the media information of file\\AGAMEMNON\Anime3\Ghibli Films\[1986] Laputa - Castle in the Sky\Das Schloss im Himmel - arte HD - 2010-04-22 - 20_15.ts ERROR: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at JMMFileHelper.MediaInfoReader.ReadMediaInfo(String fileNameFull, Boolean forceRefresh, MediaInfoResult& info) in D:\My Files\Documents\GitHub\jmmserver\JMMFileHelper\MediaInfoReader.cs:line 55
[2016-09-02 20:54:56:819] Error|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => DatabaseExtensions.InitDB Could not init database: System.NullReferenceException: Object reference not set to an instance of an object.
   at JMMServer.PlexAndKodi.Helper.GenerateFromAnimeGroup(ISession session, AnimeGroup grp, Int32 userid, List`1 allSeries) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\PlexAndKodi\Helper.cs:line 713
   at JMMServer.Entities.AnimeGroup_User.UpdatePlexKodiContracts() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\AnimeGroup_User.cs:line 133
   at JMMServer.Repositories.AnimeGroup_UserRepository.Save(AnimeGroup_User obj) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\AnimeGroup_UserRepository.cs:line 74
   at JMMServer.Repositories.AnimeGroup_UserRepository.InitCache() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\AnimeGroup_UserRepository.cs:line 44
   at JMMServer.Databases.DatabaseExtensions.InitCache(IDatabase db) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Databases\DatabaseExtensions.cs:line 108
   at JMMServer.Databases.DatabaseExtensions.InitDB(IDatabase database) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Databases\DatabaseExtensions.cs:line 82

**Comment by da3dsoul** [comment]
... That looks like my fault

**Comment by da3dsoul** [comment]
Line 713 in generate from group

**Comment by yhoogi** [comment]
Is there an estimate when the patch will be applied to the release?

**Comment by ElementalCrisis** [comment]
3.6.0.3 will be released within 12 hours.

**Comment by yhoogi** [comment]
Thanks for the fast response

.. now have to wait for resolution on MyAnime3 MP Plugin, though.

**Comment by yhoogi** [comment]
works 

Thx
