### ISSUE TITLE
After upgrading server, DatabaseExtensions.InitDB Could not init database

### ISSUE THREAD

**Issue by SubaruSumeragi** [japanesemediamanager/jmmserver#384]
After upgrading to 3.6.0.2 server can not access the database anymore

Here are the logs I have : 

[2016-09-02 23:11:10:757] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog -------------------- SYSTEM INFO -----------------------
[2016-09-02 23:11:10:802] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog JMM Server Version: v3.6.0.2
[2016-09-02 23:11:13:900] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Database Version: 53
[2016-09-02 23:11:13:905] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Operating System: Windows 8 / 2012 Server 64-bit
[2016-09-02 23:11:13:905] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Screen Size: 1920x1080
[2016-09-02 23:11:13:905] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MediaInfo DLL 0.7.86.0 (C:\Program Files (x86)\JMM Server\x64\MediaInfo.dll)
[2016-09-02 23:11:13:925] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Hasher DLL found at C:\Program Files (x86)\JMM Server\x64\hasher.dll
[2016-09-02 23:11:13:925] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog -------------------------------------------------------
[2016-09-02 23:11:13:925] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog ----------------- SERVER SETTINGS ----------------------
[2016-09-02 23:11:13:925] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog DatabaseType: MySQL
[2016-09-02 23:11:13:940] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MSSQL DatabaseServer: localhost
[2016-09-02 23:11:13:940] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MSSQL DatabaseName: JMMServer
[2016-09-02 23:11:13:940] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MSSQL DatabaseUsername: ***HIDDEN***
[2016-09-02 23:11:13:940] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MSSQL DatabasePassword: NOT SET
[2016-09-02 23:11:13:940] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog SQLITE DatabaseFile: 
[2016-09-02 23:11:13:955] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MySQL_Hostname: localhost
[2016-09-02 23:11:13:955] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MySQL_SchemaName: jmm
[2016-09-02 23:11:13:955] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MySQL_Username: ***HIDDEN***
[2016-09-02 23:11:13:955] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MySQL_Password: ***HIDDEN***
[2016-09-02 23:11:13:955] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_Username: ***HIDDEN***
[2016-09-02 23:11:13:975] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_Password: ***HIDDEN***
[2016-09-02 23:11:13:975] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_ServerAddress: api.anidb.info
[2016-09-02 23:11:13:975] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_ServerPort: 9000
[2016-09-02 23:11:13:985] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_ClientPort: 4556
[2016-09-02 23:11:13:985] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_AVDumpKey: ***HIDDEN***
[2016-09-02 23:11:13:985] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_AVDumpClientPort: 4557
[2016-09-02 23:11:13:985] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_DownloadRelatedAnime: True
[2016-09-02 23:11:13:985] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_DownloadSimilarAnime: False
[2016-09-02 23:11:14:000] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_DownloadReviews: True
[2016-09-02 23:11:14:000] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_DownloadReleaseGroups: True
[2016-09-02 23:11:14:000] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_AddFiles: False
[2016-09-02 23:11:14:000] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_StorageState: DVD
[2016-09-02 23:11:14:015] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_ReadUnwatched: True
[2016-09-02 23:11:14:015] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_ReadWatched: True
[2016-09-02 23:11:14:015] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_SetWatched: True
[2016-09-02 23:11:14:015] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_SetUnwatched: True
[2016-09-02 23:11:14:015] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_UpdateFrequency: Never
[2016-09-02 23:11:14:035] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_Calendar_UpdateFrequency: HoursTwelve
[2016-09-02 23:11:14:035] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_Anime_UpdateFrequency: WeekOne
[2016-09-02 23:11:14:035] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_Address: omm.hobbydb.net.leaf.arvixe.com
[2016-09-02 23:11:14:035] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_Anonymous: False
[2016-09-02 23:11:14:035] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_XRefFileEpisode_Get: True
[2016-09-02 23:11:14:050] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_XRefFileEpisode_Send: True
[2016-09-02 23:11:14:050] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_TvDB_Get: True
[2016-09-02 23:11:14:050] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_TvDB_Send: True
[2016-09-02 23:11:14:050] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_MAL_Get: True
[2016-09-02 23:11:14:050] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_MAL_Send: True
[2016-09-02 23:11:14:065] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_AutoFanart: True
[2016-09-02 23:11:14:065] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_AutoFanartAmount: 10
[2016-09-02 23:11:14:065] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_AutoWideBanners: True
[2016-09-02 23:11:14:065] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_AutoPosters: True
[2016-09-02 23:11:14:065] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_UpdateFrequency: Never
[2016-09-02 23:11:14:080] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_Language: en
[2016-09-02 23:11:14:080] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MovieDB_AutoFanart: True
[2016-09-02 23:11:14:080] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MovieDB_AutoFanartAmount: 10
[2016-09-02 23:11:14:080] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MovieDB_AutoPosters: True
[2016-09-02 23:11:14:080] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog VideoExtensions: MKV,AVI,MP4,MOV,OGM,WMV,MPG,MPEG,WEBM
[2016-09-02 23:11:14:095] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog DefaultSeriesLanguage: Romaji
[2016-09-02 23:11:14:095] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog DefaultEpisodeLanguage: Romaji
[2016-09-02 23:11:14:095] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog RunImportOnStart: False
[2016-09-02 23:11:14:095] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Hash_CRC32: True
[2016-09-02 23:11:14:110] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Hash_MD5: True
[2016-09-02 23:11:14:110] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Hash_SHA1: True
[2016-09-02 23:11:14:110] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Import_UseExistingFileWatchedStatus: True
[2016-09-02 23:11:14:110] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_IsEnabled: True
[2016-09-02 23:11:14:110] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_AuthToken: NOT SET
[2016-09-02 23:11:14:125] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_RefreshToken: NOT SET
[2016-09-02 23:11:14:125] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_UpdateFrequency: Never
[2016-09-02 23:11:14:125] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_SyncFrequency: Never
[2016-09-02 23:11:14:125] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AutoGroupSeries: True
[2016-09-02 23:11:14:125] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AutoGroupSeriesRelationExclusions: 
[2016-09-02 23:11:14:140] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog LanguagePreference: x-jat,en,FR
[2016-09-02 23:11:14:140] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog LanguageUseSynonyms: True
[2016-09-02 23:11:14:140] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog EpisodeTitleSource: AniDB
[2016-09-02 23:11:14:140] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog SeriesDescriptionSource: AniDB
[2016-09-02 23:11:14:140] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog SeriesNameSource: AniDB
[2016-09-02 23:11:14:155] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog BaseImagesPath: 
[2016-09-02 23:11:14:155] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog BaseImagesPathIsDefault: True
[2016-09-02 23:11:14:155] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog -------------------------------------------------------
[2016-09-02 23:11:14:310] Info|UIElement.RaiseEventImpl => EventRoute.InvokeHandlersImpl => MainWindow.MainWindow_Loaded Clearing Cache...
[2016-09-02 23:11:14:340] Info|UIElement.RaiseEventImpl => EventRoute.InvokeHandlersImpl => MainWindow.MainWindow_Loaded Initializing DB...
[2016-09-02 23:11:14:345] Info|UIElement.RaiseEventImpl => EventRoute.InvokeHandlersImpl => MainWindow.MainWindow_Loaded Checking for updates...
[2016-09-02 23:11:14:345] Info|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => MainWindow.AniDBDispose Disposing...
[2016-09-02 23:11:14:345] Info|MainWindow.workerSetupDB_DoWork => MainWindow.AniDBDispose => AniDBHelper.Dispose ANIDBLIB DISPOSING...
[2016-09-02 23:11:16:368] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork Setting up database...
[2016-09-02 23:12:00:956] Error|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => DatabaseExtensions.InitDB Could not init database: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at JMMServer.Entities.AnimeSeries.get_AirDate() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\AnimeSeries.cs:line 453
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JMMServer.Entities.AnimeGroup.GetAllSeries(ISession session) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\AnimeGroup.cs:line 573
   at JMMServer.Entities.AnimeGroup.UpdateContract(ISession session, Boolean updatestats) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\AnimeGroup.cs:line 1007
   at JMMServer.Repositories.AnimeGroupRepository.Save(AnimeGroup grp, Boolean updategrpcontractstats, Boolean recursive, Boolean verifylockedFilters) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\AnimeGroupRepository.cs:line 76
   at JMMServer.Repositories.AnimeGroupRepository.InitCache() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\AnimeGroupRepository.cs:line 35
   at JMMServer.Databases.DatabaseExtensions.InitCache(IDatabase db) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Databases\DatabaseExtensions.cs:line 108
   at JMMServer.Databases.DatabaseExtensions.InitDB(IDatabase database) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Databases\DatabaseExtensions.cs:line 83

**Comment by da3dsoul** [comment]
Looks like mine. Gimme a sec
