### ISSUE TITLE
JMM Server upgrade failed

### ISSUE THREAD

**Issue by danmarce** [japanesemediamanager/jmmserver#388]
[2016-09-02.txt](https://github.com/japanesemediamanager/jmmserver/files/453638/2016-09-02.txt)

I have a fairly large database. I run JMM in a VM just for it, while is kinda slow it always worked perfectly. I tried to run the 3.6.0.2 version. As you can see in the log, I started before 7 pm. Past 1 am it was still upgrading, so I left it to run.

After that it just hanged and I had to close it. After restarting, it hanged again and it won't open. Is good you make a backup before because I can either return to 3.5 or try again, I'll run a test with 3.6.0.3 in a WAY faster machine.

My db is so big I had to reconfigure MySQL (set global max_allowed_packet=104857600) to be able to use the backup script.

I have all the logs, and backups. I'll keep you posted.

**Comment by ElementalCrisis** [comment]
Keep in mind that the larger the database, the longer it will take when regenerating contracts. We've released two maintenance updates since 3.6.0.2 so I suggest updating as it might fix your error.

**Comment by danmarce** [comment]
New test. 3.6.0.3, its about the same point it failed in a different machine before.

![capture](https://cloud.githubusercontent.com/assets/19630538/18228063/481e80be-7200-11e6-9032-68eb5ccb37af.PNG)

The log file for the day, includes my previous attempts.

[2016-09-03.txt](https://github.com/japanesemediamanager/jmmserver/files/453681/2016-09-03.txt)

**Comment by danmarce** [comment]
3.6.0.4 Exactly at the same point. I guess something on my data produces this.
[2016-09-03.txt](https://github.com/japanesemediamanager/jmmserver/files/453703/2016-09-03.txt)
![capture](https://cloud.githubusercontent.com/assets/19630538/18228310/aa82f2fe-720e-11e6-9160-2e7154b24731.PNG)

**Comment by danmarce** [comment]
I restarted it twice and it didn't work. 

But at the 3rd restart...

![capture3](https://cloud.githubusercontent.com/assets/19630538/18228368/8c709ee0-7210-11e6-9399-0dbff8d0a7b1.PNG)

Now it seems to work again....

**Comment by danmarce** [comment]
After a while, It failed again.

Now restart does not work.

Using this, SELECT * FROM performance_schema.events_statements_current e; I got what it was doing:


SELECT `this_` . `VideoLocalID` AS `VideoLoc1_211_0_` , `this_` . `DateTimeUpdated` AS `DateTime2_211_0_` , `this_` . `DateTimeCreated` AS `DateTime3_211_0_` , `this_` . `FilePath` AS `FilePath211_0_` , `this_` . `FileSize` AS `FileSize211_0_` , `this_` . `Hash` AS `Hash211_0_` , `this_` . `CRC32` AS `CRC7_211_0_` , `this_` . `MD5` AS `MD8_211_0_` , `this_` . `SHA1` AS `SHA9_211_0_` , `this_` . `HashSource` AS `HashSource211_0_` , `this_` . `ImportFolderID` AS `ImportF11_211_0_` , `this_` . `IsIgnored` AS `IsIgnored211_0_` , `this_` . `IsVariation` AS `IsVaria13_211_0_` , `this_` . `MediaVersion` AS `MediaVe14_211_0_` , `this_` . `MediaBlob` AS `MediaBlob211_0_` , `this_` . `MediaSize` AS `MediaSize211_0_` FROM `VideoLocal` `this_`

**Comment by ElementalCrisis** [comment]
Seems it's related to your large collection, time to summon @maxpiva, he'll be able to help.

**Comment by maxpiva** [comment]
Problem is we don't have a log, why it hangs. There is no error logged seems, the regen got in an infinite loop. Will look at it. If you have any logs with error, please do upload. Also, your database was backuped before Update. (In case worst scenario happens). It can be found in DatabaseBackup directory.

**Comment by danmarce** [comment]
Yes, your idea of creating a backup before update was really, really helpful. I restored the DB from backup and went back to 3.5.0.2. It works as usual (I hashed and added files to it)

Sadly the problem is that it never gets to save an error on the log. This is the latest log, you will see how I restarted it a few times at first, it worked for a while. Then when it failed it did not worked again.

[2016-09-03.txt](https://github.com/japanesemediamanager/jmmserver/files/453767/2016-09-03.txt)

Anyway, now I keep two instances of it in separated machines, so I can test 3.6.0

**Comment by danmarce** [comment]
OK, I downloaded the source code zip file and Installed Visual Studio 2015. I had no problems building it (just had to change the default .config file)

This time the error happened, but I got WHERE it happened.

![capture2](https://cloud.githubusercontent.com/assets/19630538/18229268/293e8c88-7238-11e6-8731-9871440f9928.PNG)

System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=JMMFileHelper
  StackTrace:
       at MediaInfoLib.MediaInfo.MediaInfo_Open(IntPtr Handle, String FileName)
       at MediaInfoLib.MediaInfo.Open(String FileName) in E:\Code\jmmserver-master\JMMFileHelper\MediaInfo\MediaInfoDLL.cs:line 224
       at PlexMediaInfo.MediaConvert.Convert(String filename) in E:\Code\jmmserver-master\JMMFileHelper\MediaInfo\Convert.cs:line 457
       at JMMFileHelper.MediaInfoReader.ReadMediaInfo(String fileNameFull, Boolean forceRefresh, MediaInfoResult& info) in E:\Code\jmmserver-master\JMMFileHelper\MediaInfoReader.cs:line 44
       at JMMFileHelper.FileHashHelper.GetMediaInfo(String fileName, Boolean forceRefresh) in E:\Code\jmmserver-master\JMMFileHelper\FileHashHelper.cs:line 40
       at JMMServer.PlexAndKodi.Helper.GenerateMediaFromVideoLocal(VideoLocal v) in E:\Code\jmmserver-master\JMMServer\PlexAndKodi\Helper.cs:line 488
       at JMMServer.Repositories.VideoLocalRepository.UpdateMediaContracts(VideoLocal obj) in E:\Code\jmmserver-master\JMMServer\Repositories\VideoLocalRepository.cs:line 73
       at JMMServer.Repositories.VideoLocalRepository.Save(VideoLocal obj, Boolean updateEpisodes) in E:\Code\jmmserver-master\JMMServer\Repositories\VideoLocalRepository.cs:line 95
       at JMMServer.Repositories.VideoLocalRepository.InitCache() in E:\Code\jmmserver-master\JMMServer\Repositories\VideoLocalRepository.cs:line 41
       at JMMServer.Databases.DatabaseExtensions.InitCache(IDatabase db) in E:\Code\jmmserver-master\JMMServer\Databases\DatabaseExtensions.cs:line 100
       at JMMServer.Databases.DatabaseExtensions.InitDB(IDatabase database) in E:\Code\jmmserver-master\JMMServer\Databases\DatabaseExtensions.cs:line 82
       at JMMServer.MainWindow.workerSetupDB_DoWork(Object sender, DoWorkEventArgs e) in E:\Code\jmmserver-master\JMMServer\MainWindow.xaml.cs:line 1025
       at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
       at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
       at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
       at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
  InnerException: 



Filename is:

"\\\\SHIRAYUKI\\Public\\Anime\\Lovely Complex\\10 A Confrontation with the Ex-Girlfriend! The Epic Breast-Baring Battle!.mkv"

I tested and I was able to open the file.

**Comment by danmarce** [comment]
I updated MediaInfo.dll to 0.7.88 and Server is working. 

![capture3](https://cloud.githubusercontent.com/assets/19630538/18229346/8b2b135a-723b-11e6-862f-efbb7692f62d.PNG)

Sorry for all these posts. Will check for it to complete everything, and will do a full test later (full upgrade from 3.5.0.2)

**Comment by da3dsoul** [comment]
Nice work

**Comment by da3dsoul** [comment]
Also Yay! It's not my fault. I was worried it was based on the area it failed.

**Comment by danmarce** [comment]
MediaInfo.dll creates the problem.

Before it worked in my test not because I replaced it with a newer one, but because I made a mistake and it was not able to load the .dll.

In my second full test, it failed too. I suspected of it and I just renamed the .dll to prevent it from loading. It "worked".

I guess an option is to put a catch in that place, in case MediaInfo fails opening a file.

**Comment by ElementalCrisis** [comment]
Hmm, MediaInfo.DLL is required as without it we can't get your file information. I wonder why its failing, any ideas @maxpiva?

**Comment by maxpiva** [comment]
Probably a bug in the included version related to that special anime,
mediainfo.dll (hangs), Since we have such behavior on corrupted web streams
on 3.6.5.0 i added a timeout of 10 minutes, but that code change is in
3.6.5.0. Which includes a newer version of mediainfo.dll, anyway, will be
nice if before beta we update every dll related to mediaportal to latest
version.

Danmare could you check if that particular anime has the right hashes? (Is
Corrupted maybe?)

**Comment by danmarce** [comment]
Ok, while I tested the file playing it on MPCHC, it makes sense to consider a possible corruption.

![untitled6](https://cloud.githubusercontent.com/assets/19630538/18237858/1b7195fe-72fc-11e6-905b-f2e99293ecce.png)

Is [this one](http://anidb.net/perl-bin/animedb.pl?show=file&fid=1171370) on ANIDB.  Is the episode 10 of Lovely Complex and it is the file that kills MediaInfo.

I decided to hash it independently, so I used [Quick Hash](https://sourceforge.net/projects/quickhash/?source=typ_redirect)

Its MD5 hash, 12B81A4899E5F226DABB481A15195D64, matches the one on ANIDB, same for SHA1 D445A9BF70F7FD423D8E8831E24A8FAD5590490B.

![untitled](https://cloud.githubusercontent.com/assets/19630538/18237794/60c870c4-72fb-11e6-98c1-33e5802abf16.png)

So, the file is not corrupted and is accessible.

As a side note, and I think is not related, I discovered that I can open the file in the player and do its MD5 and SHA1 hash while it is playing, but I can't do its SHA256, it has to be closed.

**Comment by maxpiva** [comment]
Thanks for you fast response dan :)

**Comment by bigretromike** [comment]
Sometimes its not that file is corrupted but mediainfo fail to read it properly. This could happend because of many reasons. Also, with bigger collection the bigger chance you got that "special" file. As @maxpiva said, there is a timeout now added so this should help. Also we trying to have updated mediainfo in stable releases. Also Thanks for very informative research and for trying to figure it out by yourself!

**Comment by danmarce** [comment]
I forgot to report. I have updated to last stable, 3.6.1.0

Every time it starts it tries to do the mediainfo routine... and it fails.

I deleted the mediainfo.dll, it fails to load it, reports that on the log, but it starts and works.

As it was mentioned, this is likely to happen when you have a huge collection, the whole upgrade to 3.6 and the first catching took almost a day (done in the slower VM I use exclusively for JMM), but overall, it now starts WAY faster than before.

**Comment by ElementalCrisis** [comment]
Improvements have been made that drastically reduce the time it takes to regenerate your database thanks to @pmcleish. The newer MediaInfo will be in 3.6.5/3.7, thanks again for all the work on tracking down this issue!

**Comment by bigretromike** [comment]
If its fixed, please close ;-)

**Comment by ElementalCrisis** [comment]
We don't know if it's been fixed yet as we'll need to test with the newer MediaInfo file in 3.7.

**Comment by bigretromike** [comment]
Then I missread it, sorry

**Comment by ElementalCrisis** [comment]
No need to apologize, closing issues is always a good thing. :)

**Comment by bigretromike** [comment]
@ElementalCrisis time to close ?

**Comment by ElementalCrisis** [comment]
Yeah we can close.
