### ISSUE TITLE
Nancy crashes on startup

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmserver#397]
All the log gave me was this
```
[2016-09-08 11:53:28:031] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog -------------------------------------------------------
[2016-09-08 11:59:18:583] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog -------------------- SYSTEM INFO -----------------------
[2016-09-08 11:59:18:653] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog JMM Server Version: v3.7.0.0
[2016-09-08 11:59:23:557] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Database Version: 49
[2016-09-08 11:59:23:557] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Operating System: Windows 8 / 2012 Server 64-bit
[2016-09-08 11:59:23:597] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Screen Size: 3840x2160
[2016-09-08 11:59:23:612] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MediaInfo DLL 0.7.86.0 (C:\Users\da3ds\Source\Repos\jmmserver\JMMServer\bin\Debug\x64\MediaInfo.dll)
[2016-09-08 11:59:23:612] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Hasher DLL found at C:\Users\da3ds\Source\Repos\jmmserver\JMMServer\bin\Debug\x64\hasher.dll
[2016-09-08 11:59:23:612] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog -------------------------------------------------------
[2016-09-08 11:59:23:612] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog ----------------- SERVER SETTINGS ----------------------
[2016-09-08 11:59:23:612] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog DatabaseType: SQLServer
[2016-09-08 11:59:23:612] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MSSQL DatabaseServer: THE-POWERHOUSE\JMMSERVER
[2016-09-08 11:59:23:624] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MSSQL DatabaseName: JMMServerNew
[2016-09-08 11:59:23:624] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MSSQL DatabaseUsername: ***HIDDEN***
[2016-09-08 11:59:23:624] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MSSQL DatabasePassword: ***HIDDEN***
[2016-09-08 11:59:23:624] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog SQLITE DatabaseFile: 
[2016-09-08 11:59:23:624] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MySQL_Hostname: localhost
[2016-09-08 11:59:23:624] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MySQL_SchemaName: jmm
[2016-09-08 11:59:23:624] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MySQL_Username: ***HIDDEN***
[2016-09-08 11:59:23:624] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MySQL_Password: ***HIDDEN***
[2016-09-08 11:59:23:624] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_Username: ***HIDDEN***
[2016-09-08 11:59:23:624] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_Password: ***HIDDEN***
[2016-09-08 11:59:23:640] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_ServerAddress: api.anidb.info
[2016-09-08 11:59:23:640] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_ServerPort: 9000
[2016-09-08 11:59:23:640] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_ClientPort: 4556
[2016-09-08 11:59:23:640] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_AVDumpKey: ***HIDDEN***
[2016-09-08 11:59:23:640] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_AVDumpClientPort: 4557
[2016-09-08 11:59:23:640] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_DownloadRelatedAnime: True
[2016-09-08 11:59:23:640] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_DownloadSimilarAnime: False
[2016-09-08 11:59:23:640] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_DownloadReviews: False
[2016-09-08 11:59:23:640] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_DownloadReleaseGroups: True
[2016-09-08 11:59:23:655] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_AddFiles: True
[2016-09-08 11:59:23:655] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_StorageState: HDD
[2016-09-08 11:59:23:655] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_ReadUnwatched: True
[2016-09-08 11:59:23:655] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_ReadWatched: True
[2016-09-08 11:59:23:655] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_SetWatched: True
[2016-09-08 11:59:23:655] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_SetUnwatched: True
[2016-09-08 11:59:23:655] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_MyList_UpdateFrequency: HoursTwelve
[2016-09-08 11:59:23:655] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_Calendar_UpdateFrequency: Daily
[2016-09-08 11:59:23:655] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AniDB_Anime_UpdateFrequency: HoursTwelve
[2016-09-08 11:59:23:655] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_Address: omm.hobbydb.net.leaf.arvixe.com
[2016-09-08 11:59:23:671] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_Anonymous: False
[2016-09-08 11:59:23:671] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_XRefFileEpisode_Get: True
[2016-09-08 11:59:23:671] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_XRefFileEpisode_Send: True
[2016-09-08 11:59:23:671] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_TvDB_Get: True
[2016-09-08 11:59:23:671] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_TvDB_Send: True
[2016-09-08 11:59:23:671] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_MAL_Get: True
[2016-09-08 11:59:23:671] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog WebCache_MAL_Send: True
[2016-09-08 11:59:23:671] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_AutoFanart: True
[2016-09-08 11:59:23:671] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_AutoFanartAmount: 10
[2016-09-08 11:59:23:671] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_AutoWideBanners: True
[2016-09-08 11:59:23:671] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_AutoPosters: True
[2016-09-08 11:59:23:671] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_UpdateFrequency: HoursSix
[2016-09-08 11:59:23:686] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog TvDB_Language: en
[2016-09-08 11:59:23:686] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MovieDB_AutoFanart: True
[2016-09-08 11:59:23:686] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MovieDB_AutoFanartAmount: 10
[2016-09-08 11:59:23:686] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog MovieDB_AutoPosters: True
[2016-09-08 11:59:23:686] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog VideoExtensions: MKV,AVI,MP4,MOV,OGM,WMV,MPG,MPEG,MK3D
[2016-09-08 11:59:23:686] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog DefaultSeriesLanguage: Romaji
[2016-09-08 11:59:23:686] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog DefaultEpisodeLanguage: Romaji
[2016-09-08 11:59:23:686] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog RunImportOnStart: True
[2016-09-08 11:59:23:686] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Hash_CRC32: True
[2016-09-08 11:59:23:686] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Hash_MD5: True
[2016-09-08 11:59:23:686] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Hash_SHA1: True
[2016-09-08 11:59:23:686] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Import_UseExistingFileWatchedStatus: True
[2016-09-08 11:59:23:703] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_IsEnabled: True
[2016-09-08 11:59:23:703] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_AuthToken: NOT SET
[2016-09-08 11:59:23:703] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_RefreshToken: NOT SET
[2016-09-08 11:59:23:703] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_UpdateFrequency: HoursSix
[2016-09-08 11:59:23:703] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog Trakt_SyncFrequency: Never
[2016-09-08 11:59:23:703] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AutoGroupSeries: True
[2016-09-08 11:59:23:703] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog AutoGroupSeriesRelationExclusions: same setting
[2016-09-08 11:59:23:703] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog LanguagePreference: x-jat,en
[2016-09-08 11:59:23:703] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog LanguageUseSynonyms: True
[2016-09-08 11:59:23:703] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog EpisodeTitleSource: AniDB
[2016-09-08 11:59:23:703] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog SeriesDescriptionSource: AniDB
[2016-09-08 11:59:23:719] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog SeriesNameSource: AniDB
[2016-09-08 11:59:23:719] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog BaseImagesPath: 
[2016-09-08 11:59:23:719] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog BaseImagesPathIsDefault: True
[2016-09-08 11:59:23:719] Info|RuntimeTypeHandle.CreateInstance => MainWindow..ctor => ServerSettings.DebugSettingsToLog -------------------------------------------------------
```
Opening the Debugger...

**Comment by da3dsoul** [comment]
{System.Windows.Markup.XamlParseException: 'The invocation of the constructor on type 'JMMServer.MainWindow' that matches the specified binding constraints threw an exception.' Line number '4' and line position '9'. ---> System.InvalidOperationException: Something went wrong when trying to satisfy one of the dependencies during composition, make sure that you've registered all new dependencies in the container and inspect the innerexception for more details. ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Nancy.NancyEngine ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Nancy.Routing.DefaultRequestDispatcher ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Nancy.Routing.DefaultRouteResolver ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Nancy.Routing.DefaultNancyModuleBuilder ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Nancy.DefaultResponseFormatterFactory ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Nancy.ISerializer ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Nancy.TinyIoc.TinyIoCContainer.<GetTypeConstructors>b__3a(ConstructorInfo ctor)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Nancy.TinyIoc.TinyIoCContainer.GetBestConstructor(Type type, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.<ResolveAllInternal>b__43(TypeRegistration registration)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Nancy.DefaultResponseFormatterFactory..ctor(IRootPathProvider rootPathProvider, IEnumerable`1 serializers)
   at lambda_method(Closure , Object[] )
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.Resolve(Type resolveType)
   at Nancy.TinyIoc.TinyIoCContainer.Resolve[ResolveType]()
   at Nancy.DefaultNancyBootstrapper.GetEngineInternal()
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.SafeGetNancyEngineInstance()
   --- End of inner exception stack trace ---
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.SafeGetNancyEngineInstance()
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.GetEngine()
   at Nancy.Hosting.Self.NancyHost..ctor(INancyBootstrapper bootstrapper, HostConfiguration configuration, Uri[] baseUris)
   at Nancy.Hosting.Self.NancyHost..ctor(Uri[] baseUris)
   at JMMServer.MainWindow.StartNancyHost() in C:\Users\da3ds\Source\Repos\jmmserver\JMMServer\MainWindow.xaml.cs:line 2524
   at JMMServer.MainWindow..ctor() in C:\Users\da3ds\Source\Repos\jmmserver\JMMServer\MainWindow.xaml.cs:line 329
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at JMMServer.App.Main()}

**Comment by da3dsoul** [comment]
The DLL's are missing

**Comment by bigretromike** [comment]
probably thanks to merge. If this is true, then @ElementalCrisis and @hidden4003 wont be affected as they used nancy before merge and have proper dlls

**Comment by da3dsoul** [comment]
This will be closed for now. It can be reopened if applicable again
