### ISSUE TITLE
SQLite Database locked upon deleting series

### ISSUE THREAD

**Issue by Scrxtchy** [japanesemediamanager/jmmserver#430]
Upon trying to delete a series from a client, JMM Server logs that the database is locked, and the client hangs for around 20 seconds. This can be done from either a Collection screen, or Utilities screen.
Linking files to series still seems to work, so the entire db3 file is not locked up entirely
Restarting the host computer had no affect on the outcome of this issue, 
Both Desktop and Server run `v3.6.1.0`
```
[2016-09-22 16:13:42:665] Info|UIElement.RaiseEventImpl => EventRoute.InvokeHandlersImpl => MainWindow.MainWindow_Loaded Clearing Cache...
[2016-09-22 16:13:42:720] Info|UIElement.RaiseEventImpl => EventRoute.InvokeHandlersImpl => MainWindow.MainWindow_Loaded Initializing DB...
[2016-09-22 16:13:42:720] Info|UIElement.RaiseEventImpl => EventRoute.InvokeHandlersImpl => MainWindow.MainWindow_Loaded Checking for updates...
[2016-09-22 16:13:42:720] Info|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => MainWindow.AniDBDispose Disposing...
[2016-09-22 16:13:42:730] Info|MainWindow.workerSetupDB_DoWork => MainWindow.AniDBDispose => AniDBHelper.Dispose ANIDBLIB DISPOSING...
[2016-09-22 16:13:44:740] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork Setting up database...
[2016-09-22 16:13:50:272] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork Initializing Session Factory...
[2016-09-22 16:13:50:272] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork Initializing Hosts...
[2016-09-22 16:13:50:278] Info|MainWindow.SetupAniDBProcessor => AniDBHelper.Init => AniDBHelper.BindToLocalPort -------- Local IP Addresses --------
[2016-09-22 16:13:50:278] Info|MainWindow.SetupAniDBProcessor => AniDBHelper.Init => AniDBHelper.BindToLocalPort -------- End Local IP Addresses --------
[2016-09-22 16:13:50:278] Info|MainWindow.SetupAniDBProcessor => AniDBHelper.Init => AniDBHelper.BindToLocalPort BindToLocalPort: Bound to local address: 0.0.0.0:4556 - Port: 4556 (InterNetwork)
[2016-09-22 16:13:50:747] Info|MainWindow.SetupAniDBProcessor => AniDBHelper.Init => AniDBHelper.BindToRemotePort BindToRemotePort: Bound to remote address: 173.224.120.210 : 9000
[2016-09-22 16:13:50:747] Info|MainWindow.workerSetupDB_DoWork => MainWindow.SetupAniDBProcessor => AniDBHelper.Init starting logout timer...
[2016-09-22 16:13:51:131] Info|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => MainWindow.StartWatchingFiles ImportFolder found but not watching: NA || G:\Anime
[2016-09-22 16:13:51:151] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => MainWindow.workerFileEvents_DoWork Started thread for processing file creation events
[2016-09-22 16:13:51:154] Info|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => MainWindow.StartWatchingFiles ImportFolder found but not watching: NA || G:\Weebshit
[2016-09-22 16:13:51:170] Info|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => MainWindow.StartWatchingFiles Watching ImportFolder: NA || F:\Weebshit
[2016-09-22 16:14:26:844] Error|JMMServiceImplementation.IsWebCacheAdmin => AzureWebAPI.Admin_AuthUser => AzureWebAPI.SendData Error(1) in XMLServiceQueue.SendData: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at JMMServer.Providers.Azure.AzureWebAPI.SendData(String uri, String json, String verb) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\Azure\AzureWebAPI.cs:line 514
[2016-09-22 16:15:08:147] Error|SyncMethodInvoker.Invoke => <no type>.SyncInvokeDeleteAnimeSeries => JMMServiceImplementation.DeleteAnimeSeries NHibernate.TransactionException: Begin failed with SQL exception ---> System.Data.SQLite.SQLiteException: database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteTransaction..ctor(SQLiteConnection connection, Boolean deferredLock)
   at System.Data.SQLite.SQLiteConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel) in d:\CSharp\NH\nhibernate\src\NHibernate\Transaction\AdoTransaction.cs:line 130
   --- End of inner exception stack trace ---
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel) in d:\CSharp\NH\nhibernate\src\NHibernate\Transaction\AdoTransaction.cs:line 145
   at NHibernate.AdoNet.ConnectionManager.BeginTransaction() in d:\CSharp\NH\nhibernate\src\NHibernate\AdoNet\ConnectionManager.cs:line 325
   at NHibernate.Impl.SessionImpl.BeginTransaction() in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\SessionImpl.cs:line 1436
   at JMMServer.Repositories.AnimeSeries_UserRepository.Delete(Int32 id) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\AnimeSeries_UserRepository.cs:line 169
   at JMMServer.Repositories.AnimeSeriesRepository.Delete(Int32 id) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\AnimeSeriesRepository.cs:line 230
   at JMMServer.JMMServiceImplementation.DeleteAnimeSeries(Int32 animeSeriesID, Boolean deleteFiles, Boolean deleteParentGroup) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\JMMServiceImplementation.cs:line 6671
[2016-09-22 16:28:40:653] Info|SyncMethodInvoker.Invoke => <no type>.SyncInvokeGetAllTagNames => JMMServiceImplementation.GetAllTagNames GetAllTagNames  in 20.5365 ms
[2016-09-22 16:30:05:633] Info|<no type>.SyncInvokeOnlineAnimeTitleSearch => JMMServiceImplementation.OnlineAnimeTitleSearch => AzureWebAPI.Get_AnimeTitle Cache HTTP - Getting Anime Title Data From Cache: ikoku irokoi
[2016-09-22 16:30:06:862] Info|<no type>.SyncInvokeOnlineAnimeTitleSearch => JMMServiceImplementation.OnlineAnimeTitleSearch => AzureWebAPI.Get_AnimeTitle Cache HTTP - Got Anime Title Data From Cache: ikoku irokoi - 1229.0655
[2016-09-22 16:30:12:249] Info|<no type>.SyncInvokeAssociateSingleFile => JMMServiceImplementation.AssociateSingleFile => VideoLocal.MoveFileIfRequired Moving file from G:\Weebshit\[aarinfantasy]_Ikoku_Irokoi_Romantan_OVA1_[622E5ED9].avi to G:\Anime\Ikoku Irokoi Romantan\[aarinfantasy]_Ikoku_Irokoi_Romantan_OVA1_[622E5ED9].avi
[2016-09-22 16:30:13:561] Info|CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_RefreshAnime.ProcessCommand => AnimeSeries.UpdateStats Starting Updating STATS for SERIES Series: Ikoku Irokoi Romantan (1) (True - True - True)
[2016-09-22 16:30:14:381] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_AddFileToMyList.ProcessCommand Processing CommandRequest_AddFileToMyList: 8160BC5DF9BFA16B9497327A960DE754
[2016-09-22 16:30:14:770] Info|AniDBHelper.Login => AniDBCommand_Login.Process => AniDBUDPCommand.ProcessCommand AniDB UDP - UDP_RESPONSE in 352.6358 ms - 200 mCiaH LOGIN ACCEPTED
 
[2016-09-22 16:30:17:378] Info|AniDBHelper.AddFileToMyList => AniDBCommand_AddFile.Process => AniDBUDPCommand.ProcessCommand AniDB UDP - UDP_COMMAND: MYLISTADD aid=5453&generic=1&epno=1&viewed=0&state=2&s=mCiaH
[2016-09-22 16:30:17:736] Info|AniDBHelper.AddFileToMyList => AniDBCommand_AddFile.Process => AniDBUDPCommand.ProcessCommand AniDB UDP - UDP_RESPONSE_TRUNC in 357.6464ms - 210 MYLIST ENTRY ADDED
1
 
[2016-09-22 16:30:17:791] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_AddFileToMyList.ProcessCommand Adding file to list: G:\Anime\Ikoku Irokoi Romantan\[aarinfantasy]_Ikoku_Irokoi_Romantan_OVA1_[622E5ED9].avi --- 8160BC5DF9BFA16B9497327A960DE754 - 
[2016-09-22 16:30:17:825] Info|CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_RefreshAnime.ProcessCommand => AnimeSeries.UpdateStats Starting Updating STATS for SERIES Series: Ikoku Irokoi Romantan (1) (True - True - True)
[2016-09-22 16:30:43:356] Info|SyncMethodInvoker.Invoke => <no type>.SyncInvokeDeleteAnimeSeries => JMMServiceImplementation.DeleteAnimeSeries Deleting video local record and file: G:\Anime\Ikoku Irokoi Romantan\[aarinfantasy]_Ikoku_Irokoi_Romantan_OVA1_[622E5ED9] (2).avi
[2016-09-22 16:30:43:497] Info|SyncMethodInvoker.Invoke => <no type>.SyncInvokeDeleteAnimeSeries => JMMServiceImplementation.DeleteAnimeSeries Deleting video local record and file: G:\Anime\Ikoku Irokoi Romantan\[aarinfantasy]_Ikoku_Irokoi_Romantan_OVA1_[622E5ED9].avi
[2016-09-22 16:30:43:534] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_DeleteFileFromMyList.ProcessCommand Processing CommandRequest_DeleteFileFromMyList: 7DB6B4AB23F7330CCCA1791F72ABF5CC_-1
[2016-09-22 16:30:43:534] Info|AniDBHelper.DeleteFileFromMyList => AniDBCommand_DeleteFile.Process => AniDBUDPCommand.ProcessCommand AniDB UDP - UDP_COMMAND: MYLISTDEL size=195258368&ed2k=7DB6B4AB23F7330CCCA1791F72ABF5CC&s=mCiaH
[2016-09-22 16:30:43:574] Info|SyncMethodInvoker.Invoke => <no type>.SyncInvokeDeleteAnimeSeries => JMMServiceImplementation.DeleteAnimeSeries Deleting video local record and file: G:\Anime\Ikoku Irokoi Romantan\[aarinfantasy]_Ikoku_Irokoi_Romantan_OVA2_[73F242F2].avi
[2016-09-22 16:30:43:880] Info|AniDBHelper.DeleteFileFromMyList => AniDBCommand_DeleteFile.Process => AniDBUDPCommand.ProcessCommand AniDB UDP - UDP_RESPONSE_TRUNC in 340.6148ms - 211 MYLIST ENTRY DELETED
1
 
[2016-09-22 16:30:43:880] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_DeleteFileFromMyList.ProcessCommand Deleting file from list: 7DB6B4AB23F7330CCCA1791F72ABF5CC_-1
[2016-09-22 16:31:13:695] Error|SyncMethodInvoker.Invoke => <no type>.SyncInvokeDeleteAnimeSeries => JMMServiceImplementation.DeleteAnimeSeries NHibernate.TransactionException: Begin failed with SQL exception ---> System.Data.SQLite.SQLiteException: database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteTransaction..ctor(SQLiteConnection connection, Boolean deferredLock)
   at System.Data.SQLite.SQLiteConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel) in d:\CSharp\NH\nhibernate\src\NHibernate\Transaction\AdoTransaction.cs:line 130
   --- End of inner exception stack trace ---
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel) in d:\CSharp\NH\nhibernate\src\NHibernate\Transaction\AdoTransaction.cs:line 145
   at NHibernate.AdoNet.ConnectionManager.BeginTransaction() in d:\CSharp\NH\nhibernate\src\NHibernate\AdoNet\ConnectionManager.cs:line 325
   at NHibernate.Impl.SessionImpl.BeginTransaction() in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\SessionImpl.cs:line 1436
   at JMMServer.Repositories.AnimeSeries_UserRepository.Delete(Int32 id) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\AnimeSeries_UserRepository.cs:line 169
   at JMMServer.Repositories.AnimeSeriesRepository.Delete(Int32 id) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\AnimeSeriesRepository.cs:line 230
   at JMMServer.JMMServiceImplementation.DeleteAnimeSeries(Int32 animeSeriesID, Boolean deleteFiles, Boolean deleteParentGroup) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\JMMServiceImplementation.cs:line 6671
[2016-09-22 16:31:13:788] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_DeleteFileFromMyList.ProcessCommand Processing CommandRequest_DeleteFileFromMyList: 8160BC5DF9BFA16B9497327A960DE754_-1
[2016-09-22 16:31:13:793] Info|AniDBHelper.DeleteFileFromMyList => AniDBCommand_DeleteFile.Process => AniDBUDPCommand.ProcessCommand AniDB UDP - UDP_COMMAND: MYLISTDEL size=195258368&ed2k=8160BC5DF9BFA16B9497327A960DE754&s=mCiaH
[2016-09-22 16:31:14:168] Info|AniDBHelper.DeleteFileFromMyList => AniDBCommand_DeleteFile.Process => AniDBUDPCommand.ProcessCommand AniDB UDP - UDP_RESPONSE in 374.6653 ms - 320 NO SUCH FILE```
 ```

**Comment by maxpiva** [comment]
Repositories and open transaction are more encapsulated in the latest Repository refactor, if it can be replicated on master, please re-open.
