### ISSUE TITLE
CreateCharacters error during import

### ISSUE THREAD

**Issue by RickDB** [japanesemediamanager/jmmserver#448]
**Issue**

During import it will report errors related to JMMServer.Entities.AniDB_Character.CharDescription and fail to continue updating the other items after that.
Seems related to recent NHibernate changes:
```
[2016-09-27 17:58:08:821] Info|AniDBCommand_GetFileInfo.Process => AniDBUDPCommand.ProcessCommand => JMMService.LogToSystem AniDB UDP - UDP_RESPONSE_TRUNC in 250ms - 220 FILE
1608073|10318|156685|0|201285349||0|0|732182316|b61399e39a06504ca89bcad74b44639b|bd0b29b68c0aba9288261da5309a3aa9|f2b300a607d8500c471dc7f7c177347bd77fc168|9dec2522|high|Blu-ray|AAC|128|H264/AVC|1157|1280x720|mkv|german|none|4552||1405728000|Pocket Monsters XY: Hakai no Mayu to Diancie - 1 - Complete Movie - [RAW](9dec2522).mkv|1|0|0|0||||1|Complete Movie|||0|0|raw/unknown|raw
 
[2016-09-27 17:58:08:821] Trace|CommandRequest_ProcessFile.ProcessCommand => CommandRequest_ProcessFile.ProcessFile_AniDB => AniDBHelper.GetFileInfo ProcessResult_GetFileInfo: Raw_AniDB_File:: hash: B61399E39A06504CA89BCAD74B44639B | fileID: 1608073 | Source: Blu-ray | animeID: 10318 | IsWatched: 0 | FileName: Pocket Monsters XY: Hakai no Mayu to Diancie - 1 - Complete Movie - [RAW](9dec2522).mkv | FileSize: 732182316 | DateTimeUpdated: 9/27/2016 5:58:08 PM | EpisodesRAW: 156685 | EpisodesPercentRAW: 100 | LanguagesRAW: german | SubtitlesRAW: none
[2016-09-27 17:58:08:884] Trace|AniDB_File.CreateCrossEpisodes => BaseCachedRepository`2.Save => <>c.<.ctor>b__7_0 Updating group stats by file from CrossRef_File_EpisodeRepository.Save: B61399E39A06504CA89BCAD74B44639B
[2016-09-27 17:58:08:884] Debug|CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_ProcessFile.ProcessCommand => CommandRequest_ProcessFile.ProcessFile_AniDB Getting Anime record from AniDB....
[2016-09-27 17:58:11:337] Info|AniDBHTTPCommand_GetFullAnime.Process => AniDBHTTPHelper.GetAnimeXMLFromAPI => JMMService.LogToSystem AniDB HTTP - Getting anime XML data from AniDB: 10318
[2016-09-27 17:58:11:884] Info|AniDBHTTPCommand_GetFullAnime.Process => AniDBHTTPHelper.GetAnimeXMLFromAPI => JMMService.LogToSystem AniDB HTTP - Got anime XML Data From AniDB: 10318 - 546.875 - <?xml version="1.0" encoding="UTF-8"?><anime id="10318" restricted="false">
<type>Movie</type>
<epis
[2016-09-27 17:58:12:993] Trace|AniDBHelper.GetAnimeInfoHTTP => AniDBHelper.GetAnimeInfoHTTP => AniDBHelper.SaveResultsForAnimeXML cmdResult.Anime: AnimeID: 10318 | Main Title: Pocket Monsters XY: Hakai no Mayu to Diancie | EpisodeCount: 1 | AirDate: 7/19/2014 12:00:00 AM | Picname: 156036.jpg | Type: Movie | relatedAnimeIDs: 10746'9956'10319 | relatedAnimeTypes: 2'52'100
[2016-09-27 17:58:14:087] Trace|AniDBHelper.GetAnimeInfoHTTP => AniDBHelper.SaveResultsForAnimeXML => AniDB_Anime.PopulateAndSaveFromHTTP ------------------------------------------------
[2016-09-27 17:58:15:149] Trace|AniDBHelper.GetAnimeInfoHTTP => AniDBHelper.SaveResultsForAnimeXML => AniDB_Anime.PopulateAndSaveFromHTTP PopulateAndSaveFromHTTP: for 10318 - Pocket Monsters XY: Hakai no Mayu to Diancie
[2016-09-27 17:58:16:228] Trace|AniDBHelper.GetAnimeInfoHTTP => AniDBHelper.SaveResultsForAnimeXML => AniDB_Anime.PopulateAndSaveFromHTTP ------------------------------------------------
[2016-09-27 17:58:16:321] Trace|AniDBHelper.GetAnimeInfoHTTP => AniDBHelper.SaveResultsForAnimeXML => AniDB_Anime.PopulateAndSaveFromHTTP CreateEpisodes in : 2
[2016-09-27 17:58:16:337] Trace|AniDBHelper.GetAnimeInfoHTTP => AniDBHelper.SaveResultsForAnimeXML => AniDB_Anime.PopulateAndSaveFromHTTP CreateTitles in : 5
[2016-09-27 17:58:16:353] Trace|AniDBHelper.GetAnimeInfoHTTP => AniDBHelper.SaveResultsForAnimeXML => AniDB_Anime.PopulateAndSaveFromHTTP CreateTags in : 11
[2016-09-27 17:58:16:618] Error|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_ProcessFile.ProcessCommand Error processing CommandRequest_ProcessFile: 15 - NHibernate.PropertyValueException: Error dehydrating property value for JMMServer.Entities.AniDB_Character.CharDescription ---> NHibernate.HibernateException: The length of the string value exceeds the length configured in the mapping/parameter.
   at NHibernate.Type.AbstractStringType.Set(IDbCommand cmd, Object value, Int32 index)
   at NHibernate.Type.NullableType.NullSafeSet(IDbCommand cmd, Object value, Int32 index)
   at NHibernate.Type.NullableType.NullSafeSet(IDbCommand st, Object value, Int32 index, Boolean[] settable, ISessionImplementor session)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Dehydrate(Object id, Object[] fields, Object rowId, Boolean[] includeProperty, Boolean[][] includeColumns, Int32 table, IDbCommand statement, ISessionImplementor session, Int32 index)
   --- End of inner exception stack trace ---
   at NHibernate.Persister.Entity.AbstractEntityPersister.Dehydrate(Object id, Object[] fields, Object rowId, Boolean[] includeProperty, Boolean[][] includeColumns, Int32 table, IDbCommand statement, ISessionImplementor session, Int32 index)
   at NHibernate.Persister.Entity.AbstractEntityPersister.GeneratedIdentifierBinder.BindValues(IDbCommand ps)
   at NHibernate.Id.Insert.AbstractReturningDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Boolean[] notNull, SqlCommandInfo sql, Object obj, ISessionImplementor session)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session)
   at NHibernate.Action.EntityIdentityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSave(Object entity, Object id, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.PerformSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.SaveOrUpdate(Object obj)
   at JMMServer.Repositories.BaseDirectRepository`2.Save(List`1 objs)
   at JMMServer.Entities.AniDB_Anime.CreateCharacters(ISession session, List`1 chars)
   at JMMServer.Entities.AniDB_Anime.PopulateAndSaveFromHTTP(ISession session, Raw_AniDB_Anime animeInfo, List`1 eps, List`1 titles, List`1 cats, List`1 tags, List`1 chars, List`1 rels, List`1 sims, List`1 recs, Boolean downloadRelations)
   at JMMServer.AniDBHelper.SaveResultsForAnimeXML(ISession session, Int32 animeID, Boolean downloadRelations, AniDBHTTPCommand_GetFullAnime getAnimeCmd)
   at JMMServer.AniDBHelper.GetAnimeInfoHTTP(ISession session, Int32 animeID, Boolean forceRefresh, Boolean downloadRelations)
   at JMMServer.AniDBHelper.GetAnimeInfoHTTP(Int32 animeID, Boolean forceRefresh, Boolean downloadRelations)
   at JMMServer.Commands.CommandRequest_ProcessFile.ProcessFile_AniDB(VideoLocal vidLocal)
   at JMMServer.Commands.CommandRequest_ProcessFile.ProcessCommand()
```

**To reproduce**

Create fresh database and run import over any Anime folder.

**Comment by RickDB** [comment]
@Baine found the cause and is related to default NHibernate string max value of 4000:

http://stackoverflow.com/questions/12708171/the-length-of-the-string-value-exceeds-the-length-configured-in-the-mapping-para

Used fix mentioned there with good results, might have other areas where we run into this so double checking that now.
