### ISSUE TITLE
SQL Server errors

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#45]
**Reported by Craige1Emmott, Feb 10, 2013**

Using Refresh button on the mssql setup page shows a blank error.

JMM Server can not make a connection to MSSQL server. Something to do with SOM references in the vs project, causing errors with missing dll's. Error might only occur on systems that don't have mssql server installed (jmm and sql server on different machines).

```
[2013-02-10 18:36:45:878] Error|EventRoute.InvokeHandlersImpl => RoutedEventHandlerInfo.InvokeHandler => MainWindow.btnRefreshMSSQLServerList_Click Microsoft.SqlServer.Management.Smo.FailedOperationException ---> Microsoft.SqlServer.Management.Sdk.Sfc.EnumeratorException: Failed to retrieve data for this request. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.SqlServer.SqlClrProvider, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.SqlServer.SqlClrProvider, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'
   at Microsoft.SqlServer.Management.Sdk.Sfc.ObjectLoadInfoManager.LoadHierarchy()
   at Microsoft.SqlServer.Management.Sdk.Sfc.ObjectLoadInfoManager.GetFirstObjectLoadInfo(Urn urn)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetServerVersion(Urn urn, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetObjectInfo(Object ci, RequestObjectInfo req)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetObjectInfo(Object connectionInfo, RequestObjectInfo requestObjectInfo)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.FixPropertyList(Object connectionInfo, Urn urn, String[] fields, RequestFieldsTypes requestFieldsType)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.Process(Object connectionInfo, Request request)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.Process(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Urn urn)
   at Microsoft.SqlServer.Management.Smo.SmoApplication.EnumAvailableSqlServers()
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Smo.SmoApplication.EnumAvailableSqlServers()
   at JMMServer.MainWindow.btnRefreshMSSQLServerList_Click(Object sender, RoutedEventArgs e) in C:\Projects\SVN\JMM\trunk\JMMServer\JMMServer\MainWindow.xaml.cs:line 738
[2013-02-10 18:36:48:858] Info|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => MainWindow.AniDBDispose Disposing...
[2013-02-10 18:36:48:858] Info|MainWindow.workerSetupDB_DoWork => MainWindow.AniDBDispose => AniDBHelper.Dispose ANIDBLIB DISPOSING...
[2013-02-10 18:36:50:902] Error|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => DatabaseHelper.InitDB Database: JMMServer does not exist
[2013-02-10 18:36:50:902] Error|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => DatabaseHelper.InitDB Could not init database: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.SqlServer.SqlClrProvider, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.SqlServer.SqlClrProvider, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'
   at Microsoft.SqlServer.Management.Common.ConnectionManager.CallerHavePermissionToUseSQLCLR()
   at Microsoft.SqlServer.Management.Common.ConnectionManager..ctor()
   at Microsoft.SqlServer.Management.Common.ServerConnection..ctor(String serverInstance, String userName, String password)
   at JMMServer.Databases.SQLServer.CreateDatabase() in C:\Projects\SVN\JMM\trunk\JMMServer\JMMServer\Databases\SQLServer.cs:line 125
   at JMMServer.Databases.DatabaseHelper.InitDB() in C:\Projects\SVN\JMM\trunk\JMMServer\JMMServer\Databases\DatabaseHelper.cs:line 70
```

**Comment by maxpiva** [comment]
Missing dll?, i'll close it for now.
