### ISSUE TITLE
Error When Hashing Files

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmserver#453]
When attempting to import files, I'm getting the following error messages.

```
[2016-10-01 16:34:24:010] Error|BackgroundWorker.OnDoWork => CommandProcessorHasher.workerCommands_DoWork => CommandRequest_HashFile.ProcessCommand Error processing CommandRequest_ProcessFile: E:\Anime1\Trigun.Badlands.Rumble.2010.720p.BluRay.x264-THHT.mkv - System.NullReferenceException: Object reference not set to an instance of an object.
   at JMMServer.Commands.CommandRequest_HashFile.FillVideoHashes(VideoLocal v) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Commands\CommandRequest_HashFile.cs:line 378
   at JMMServer.Commands.CommandRequest_HashFile.ProcessFile_LocalInfo() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Commands\CommandRequest_HashFile.cs:line 248
   at JMMServer.Commands.CommandRequest_HashFile.ProcessCommand() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Commands\CommandRequest_HashFile.cs:line 61
[2016-10-01 16:34:37:336] Error|MainWindow.workerFileEvents_DoWork => Importer.RunImport_ImportFolderNewFiles => Importer.IsNetworkShare System.ArgumentException: Object must be a root directory ("C:\") or a drive letter ("C").
   at System.IO.DriveInfo..ctor(String driveName)
   at JMMServer.Importer.IsNetworkShare(String ImportFolderLocation) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Importer.cs:line 464
```

My import folders are on local drives, I do have a Google Cloud Account added but those files have already been imported. 

@Baine has also gotten this error on 3.7 as well.

**Comment by maxpiva** [comment]
Already fixed but not on master.

**Comment by ElementalCrisis** [comment]
Oh Awesome. :) 

I'll close this issue once the fix is on master.

**Comment by maxpiva** [comment]
In master
