### ISSUE TITLE
[DEV] Deleting local file results in access denied exception

### ISSUE THREAD

**Issue by t0815** [japanesemediamanager/jmmserver#489]
hello,

an other issue i came accross with current dev branch. Deleting local files now always results in an access denied exception.

---
<code>
[2016-10-23 11:25:56:714] Info|SyncMethodInvoker.Invoke => <no type>.SyncInvokeDeleteVideoLocalPlaceAndFile => JMMServiceImplementation.DeleteVideoLocalPlaceAndFile Deleting video local record and file: H:\Captain Earth\[WhyNot] Captain Earth - 02 [BC3AE5BC].mkv
[2016-10-23 11:25:56:757] Error|SyncMethodInvoker.Invoke => <no type>.SyncInvokeDeleteVideoLocalPlaceAndFile => JMMServiceImplementation.DeleteVideoLocalPlaceAndFile System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'H:\Captain Earth\\[WhyNot] Captain Earth - 02 [BC3AE5BC].mkv' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalFile.<DeleteAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.SyncExtensions.<>c__DisplayClass7_0.<<Delete>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NutzCode.CloudFileSystem.SyncExtensions.Delete(IObject obj, Boolean skipTrash)
   at JMMServer.JMMServiceImplementation.DeleteVideoLocalPlaceAndFile(Int32 videolocalplaceid)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'H:\Captain Earth\\[WhyNot] Captain Earth - 02 [BC3AE5BC].mkv' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalFile.<DeleteAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.SyncExtensions.<>c__DisplayClass7_0.<<Delete>b__0>d.MoveNext()<---
</code>

I did change file permissions and set my account as owner with full access (Administrator)
but it didnt fix the problem.

Next thing i did try, was running jmmserver as Administrator, but didnt fix the issue either.

If i delete the file manually, its working.

**Comment by t0815** [comment]
issue can be closed. Was my own stupidity. Whole disk was somehow set to write-protected.....
