### ISSUE TITLE
Missing indices causing timeout exceptions using default MySQL installation

### ISSUE THREAD

**Issue by t0815** [japanesemediamanager/jmmserver#500]
As previously found in issue #496, there are some heavy queries that cause a timeout exception using
default mySQL Server installation.

I did some more testing and came across another query that takes too long, causing JmmServer to
not start.

```
[2016-10-30 07:20:12:893] Error|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => DatabaseFactory.InitDB Could not init database: NHibernate.Exceptions.GenericADOException: could not execute query
[ SELECT DISTINCT anime.AnimeID, anime.MainTitle, lan.LanguageName FROM AnimeSeries ser  INNER JOIN AniDB_Anime anime on anime.AnimeID = ser.AniDB_ID INNER JOIN AnimeEpisode ep on ep.AnimeSeriesID = ser.AnimeSeriesID INNER JOIN AniDB_Episode aniep on ep.AniDB_EpisodeID = aniep.EpisodeID INNER JOIN CrossRef_File_Episode xref on aniep.EpisodeID = xref.EpisodeID INNER JOIN AniDB_File anifile on anifile.Hash = xref.Hash INNER JOIN CrossRef_Languages_AniDB_File audio on audio.FileID = anifile.FileID INNER JOIN Language lan on audio.LanguageID = lan.LanguageID WHERE anime.AnimeID  IN (6662,8132,9980) ]
[SQL: SELECT DISTINCT anime.AnimeID, anime.MainTitle, lan.LanguageName FROM AnimeSeries ser  INNER JOIN AniDB_Anime anime on anime.AnimeID = ser.AniDB_ID INNER JOIN AnimeEpisode ep on ep.AnimeSeriesID = ser.AnimeSeriesID INNER JOIN AniDB_Episode aniep on ep.AniDB_EpisodeID = aniep.EpisodeID INNER JOIN CrossRef_File_Episode xref on aniep.EpisodeID = xref.EpisodeID INNER JOIN AniDB_File anifile on anifile.Hash = xref.Hash INNER JOIN CrossRef_Languages_AniDB_File audio on audio.FileID = anifile.FileID INNER JOIN Language lan on audio.LanguageID = lan.LanguageID WHERE anime.AnimeID  IN (6662,8132,9980)] ---> MySql.Data.MySqlClient.MySqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.TimeoutException: Timeout in IO operation
   at MySql.Data.MySqlClient.TimedStream.StopTimer()
   at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.HandleTimeoutOrThreadAbort(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Impl.SessionImpl.ListCustomQuery(ICustomQuery customQuery, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(NativeSQLQuerySpecification spec, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List[T](NativeSQLQuerySpecification spec, QueryParameters queryParameters)
   at NHibernate.Impl.SqlQueryImpl.List[T]()
   at JMMServer.Repositories.AdhocRepository.GetAudioLanguageStatsByAnimeResults(ISessionWrapper session, String animeIdPredicate)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at JMMServer.Entities.AnimeGroup.BatchUpdateContracts(ISessionWrapper session, IReadOnlyCollection`1 animeGroups, Boolean updateStats)
   at JMMServer.Entities.AnimeGroup.UpdateContract(ISessionWrapper session, Boolean updatestats)
   at JMMServer.Repositories.Cached.AnimeGroupRepository.Save(AnimeGroup grp, Boolean updategrpcontractstats, Boolean recursive, Boolean verifylockedFilters)
   at JMMServer.Repositories.Cached.AnimeGroupRepository.RegenerateDb()
   at JMMServer.Repositories.RepoFactory.Init()
   at JMMServer.Databases.DatabaseFactory.InitDB()
```

tested in mySQL client, above query took 34secs,

i do assume its the join .hash (string) thats causing the slowness. I will add index on `anifile.Hash , xref.Hash`

and test again.

**Comment by t0815** [comment]
Well. Even with BTREE index, query takes that long. 

anifile.Hash already had a BTREE index,
xref.Hash didn't, but i didn't change timings.

It seems to happen for series with many episodes during contract recreation.

Result for that query (for my DB) is:

```
9980	Fairy Tail (2014)	japanese
6662	Fairy Tail	japanese
8132	Fairy Tail (2011)	japanese
```

(I did some manual DB maintenence, so i had to let JMMServer recreate caches)

**Comment by pmcleish** [comment]
I don't currently have access to my test MySQL database so I can't check myself. But I have noticed a couple of potential missing indexes:
```
CREATE INDEX IX_CrossRef_Languages_AniDB_File_FileID ON CrossRef_Languages_AniDB_File (FileID);
CREATE INDEX IX_CrossRef_Subtitles_AniDB_File_FileID ON CrossRef_Subtitles_AniDB_File (FileID);
```
(The second one is for a similar query that will probably be encountered around the same time).
Would it be possible for you to try those indexes to see if they make any difference?

**Comment by t0815** [comment]
hm, issue can be closed. Can't reproduce the problem now. Might have been a temporary mySQL server screw-up. I did restart service tho, so maybe it was mySQL related. I did test the query in client too, and i certainly did get those timings. (checked mySQL slow log too and it was there).

No clue, why it performs fast now. Roughly ~2secs.

**Comment by pmcleish** [comment]
I've done some testing against my test MySQL database and couldn't replicate the long query duration either. It take approx 0.5s to execute with my data usually. I applied the above 3 indexes and the query for me then takes 0.01s on average (It changes the query plan by replacing an expensive Full Table Scan with an Index Range Scan). So it may still be beneficial to add these indexes at some point.
